<?php

namespace App\Jobs;

use App\Enums\IssueStatus;
use App\Models\Issue;
use App\Models\IssueLog;
use App\Services\ClaudeCodeService;
use App\Services\GitHubService;
use App\Services\IssueService;
use App\Services\PreviewService;
use App\Services\SlackService;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class ExecuteTaskJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public int $timeout = 3600;

    public function __construct(
        public int $issueNumber,
        public ?string $feedbackComment = null
    ) {
        $this->onQueue('sdd');
    }

    public function handle(
        IssueService $issueService,
        ClaudeCodeService $claudeService,
        GitHubService $githubService,
        SlackService $slackService,
        PreviewService $previewService,
    ): void {
        $issue = Issue::where('issue_number', $this->issueNumber)->firstOrFail();

        $isResume = $this->feedbackComment !== null;
        $featureBranch = $issue->feature_branch ?? "feature/issue-{$this->issueNumber}";

        if (!$issue->feature_branch) {
            $issueService->saveFeatureBranch($issue, $featureBranch);
        }

        $issueService->transitionTo($issue, IssueStatus::Developing);

        $issueWorkspacePath = $previewService->issueWorkspacePath($this->issueNumber);

        if (!$isResume) {
            $previewService->setup($issue, $featureBranch);
        }

        $prompt = $isResume
            ? $this->buildResumePrompt($issue, $this->feedbackComment)
            : $this->buildFirstRunPrompt($issue, $featureBranch);

        $sessionId = $issue->dev_session_id;

        $result = $claudeService->execute($prompt, $issueWorkspacePath, $sessionId);

        if (empty($issue->dev_session_id) && $result['session_id']) {
            $issueService->saveDevSessionId($issue, $result['session_id']);
        }

        IssueLog::create([
            'issue_id' => $issue->id,
            'job_type' => 'execute_task',
            'session_id' => $result['session_id'],
            'prompt' => $prompt,
            'output' => $result['output'],
            'exit_code' => $result['exit_code'],
            'duration_seconds' => $result['duration_seconds'],
        ]);

        $previewService->buildFrontend($issueWorkspacePath);

        $this->postComment($githubService, $result);

        $slackService->notifyPm(
            $issue->github_author,
            "Issue #{$this->issueNumber} updated based on your feedback. Preview refreshed."
        );
    }

    private function buildFirstRunPrompt(Issue $issue, string $featureBranch): string
    {
        return <<<PROMPT
            你正在根據以下規格實作一個功能。

            ## Issue #{$issue->issue_number}: {$issue->title}

            {$issue->body}

            ## 指示

            1. 建立功能分支：{$featureBranch}
            2. 分析需求
            3. 在 waltily 和/或 waltily-frontend 專案中實作該功能
            4. 如適用，撰寫測試
            PROMPT;
    }

    private function buildResumePrompt(Issue $issue, string $feedback): string
    {
        return <<<PROMPT
            PM 已針對 issue #{$issue->issue_number} 的實作提供回饋。

            ## PM 回饋

            {$feedback}

            ## 指示

            處理回饋意見，更新實作內容。
            PROMPT;
    }

    private function postComment(GitHubService $githubService, array $result): void
    {
        $sddRepo = config('sdd.github.sdd_repo');
        $parsed = json_decode($result['output'], true);
        $claudeResponse = ($parsed['result'] ?? $result['output']) . "\n\n---\n\n*This comment was generated by Claude.*";
        $githubService->postComment($sddRepo, $this->issueNumber, $claudeResponse);
    }
}
